[package]
name = "striczkof_io"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.4", features = ["rustls-0_21"] }
rustls = "0.21.6"
rustls-pemfile = "1.0.3"
sailfish = "0.8.0"
getopts = "0.2"
libloading = "0.8"

[features]
default = []
compiled_tls = []