[package]
name = "striczkof-io"
version = "0.1.1"
edition = "2021"
rust-version = "1.74.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.4", features = ["rustls-0_21"] }
actix-files = "0.6"
rustls = "0.21"
rustls-pemfile = "1.0"
ed25519-dalek = "2.1.0"
sailfish = "0.8"
getopts = "0.2"
#libloading = "0.8"
prost = "0.12"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.19"
hex = "0.4.3"

[build-dependencies]
prost-build = { version = "0.12" }

[features]
compiled_tls = []