PORTNAME=		striczkof-io
PORTVERSION=	0
PORTREVISION=	1
CATEGORIES=		www
DISTNAME=		striczkof-io

PKGNAMESUFFIX=	-devel
USE_GITHUB=		yes
GH_ACCOUNT=		striczkof

USES=		cargo


MAINTAINER=		alvin@striczkof.io
COMMENT=		My pathetic attempt of making my own web server + website with mostly Rust stuff.
WWW=			https://striczkof.io

LICENSE=		AGPLv3+
LICENSE_FILE=	${WRKSRC}/LICENSE

.include <bsd.port.mk>
