name: Prepare, build and package for release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  package:
    name: Build and package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name:
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          copyback: false
          prepare: |
            pkg install -y rust cmake
          run: |
            cargo test --verbose
