name: Prepare, build and package for release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  package:
    name: Build and package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make port in a FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          copyback: false
          prepare: |
            mkdir -p /usr/local/etc/pkg/repos 
            echo "FreeBSD: { url: "pkg+http://pkg.freebsd.org/\${ABI}/latest" }" \
              > /usr/local/etc/pkg/repos/FreeBSD.conf
            pkg update
            pkg install -y rust cmake
          run: |
            make
