name: Build and test

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_on_linux:
    name: Test on Linux (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
  build_on_freebsd:
    name: Test on FreeBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests inside a FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          copyback: false
          prepare: |
            pkg install -y rust cmake
          run: |
            cargo test --verbose
